export const headerActionTypes = {
    SET_CURRENT_LANGUAGE : 'SET_CURRENT_LANGUAGE',
    SET_CURRENT_COUNTRY : 'SET_CURRENT_COUNTRY',
    SET_CURRENT_CATEGORY : 'SET_CURRENT_CATEGORY',
    SET_ARTICLES_LIMIT : 'SET_ARTICLES_LIMIT'
}